# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-sma62UwAP_1Xto2DFTrRPrVwsdNAmbU
"""

import random
def respond(user_input):
    user_input_lower = user_input.lower().strip()

    # Specific polite responses
    if user_input_lower in ["okay", "ok", "alright"]:
        return "I’m glad I could help! If there’s anything more I can do, just let me know."

    elif user_input_lower in ["thank you", "thanks", "thx"]:
        return "You’re welcome! 😊"

    # Feature info
    elif "what can you do" in user_input_lower or "features" in user_input_lower or "what else" in user_input_lower:
        return (
            "I can help you with:\n"
            "- Answering general questions and chit-chat\n"
            "- Telling jokes 😄\n"
            "- Solving basic math problems\n"
            "- Providing study resources (Math, Python, History, Science)\n"
            "- Giving basic disease prediction based on symptoms\n"
        )

    # Check for jokes
    elif "joke" in user_input_lower:
        return random.choice(jokes)

    # Check for math problems
    elif any(char.isdigit() for char in user_input_lower):
        return solve_math(user_input_lower)

    # Study resources
    elif "study" in user_input_lower or "resources" in user_input_lower:
        for sub in ["math", "python", "history", "science"]:
            if sub in user_input_lower:
                return provide_study_resources(sub)
        return "Please specify the subject (math, python, history, science)."

    # Disease prediction
    elif "symptoms" in user_input_lower or "predict" in user_input_lower:
        symptoms = user_input_lower.split("symptoms")[-1].strip()
        symptoms = symptoms.split(",")
        return predict_disease(symptoms)

    # Greetings and chit-chat
    elif user_input_lower in ["hello", "hi", "hey", "greetings"]:
        return random.choice(["Hello!", "Hi there!", "Hey!", "Greetings!"])

    elif "how are you" in user_input_lower:
        return "I’m just a bot, but I’m doing well! How about you?"

    elif "what's up" in user_input_lower or "whats up" in user_input_lower:
        return chit_chat(user_input_lower)

    # Farewell
    elif "bye" in user_input_lower or "goodbye" in user_input_lower:
        return "Goodbye! It was nice talking to you!"

    # Default fallback
    else:
        return chit_chat(user_input_lower)

import streamlit as st

# Title of the chatbot
st.title("ChatBuddy 🤖")

# Session state keeps chat history
if 'messages' not in st.session_state:
    st.session_state.messages = []

# Text input for the user
user_input = st.text_input("You:")

# When user enters text, generate response
if user_input:
    response = respond(user_input)  # your existing respond() function
    st.session_state.messages.append({"user": user_input, "bot": response})

# Display all previous messages
for msg in st.session_state.messages:
    st.write("You: " + msg["user"])
    st.write("Bot: " + msg["bot"])
